env:
- GO111MODULE=on
before:
  hooks:
  - go mod download
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - dragonfly
  - freebsd
  - linux
  - netbsd
  - openbsd
  - solaris
  - windows
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -X main.AppName={{ .ProjectName }}
  - -X main.Version={{ .Version }}
  - -X main.Revision={{ .FullCommit }}
universal_binaries:
- replace: true
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: "{{ .ProjectName }}_sha256sums.txt"
  algorithm: sha256
changelog:
  sort: asc
  groups:
  - title: 'Features'
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: 'Bug fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: 'Others'
    order: 999
  filters:
    exclude:
    - '^docs:'
    - typo
    - (?i)foo
release:
  prerelease: auto
