name: CI
on:
  push:
    paths:
    # Go
    - '**.go'
    - '**/go.mod'
    - '**/go.sum'
    # GoReleaser
    - '.goreleaser.yml'
    # GitHub Actions
    - '.github/workflows/ci.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu
        - windows
        - macos
        go:
        - '1.13'
        - '1.14'
        - '1.15'
        - '1.16'
        - '1.17'
    env:
      RELEASE_OS_DISTRIB: ubuntu
      RELEASE_GO_VERSION: '1.17'
    runs-on: ${{ matrix.os }}-latest
    name: Go ${{ matrix.go }} (${{ matrix.os }})
    defaults:
      run:
        shell: bash
    steps:
    ################################################################################
    # Checkout
    ################################################################################
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ startsWith(github.ref, 'refs/tags/') && '0' || '1' }}
    ################################################################################
    # Setup
    ################################################################################
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    ################################################################################
    # Cache
    ################################################################################
    - name: Go Cache Directory
      id: go-cache-paths
      run: |
        GOCACHE="$(go env GOCACHE)"
        GOMODCACHE="$(go env GOMODCACHE)"
        test -z "${GOCACHE}" && GOCACHE="${HOME}/.cache/go-build"
        test -z "${GOMODCACHE}" && GOMODCACHE="$(go env GOPATH)/pkg/mod"
        echo "::set-output name=go-build::${GOCACHE}"
        echo "::set-output name=go-mod::${GOMODCACHE}"
    - name: Go Build Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-${{ matrix.go }}-build-${{ hashFiles('**/go.sum') }}
    - name: Go Mod Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-${{ matrix.go }}-mod-${{ hashFiles('**/go.sum') }}
    ################################################################################
    # Go
    ################################################################################
    - name: Go Mod Download
      run: make download
    - name: Go Mod Tidy
      run: make tidy
    - name: Go Tools
      run: make tools
    - name: Go Fmt
      run: make fmt
    - name: Go Vet
      run: make vet
    - name: Go Lint
      run: make lint
    - name: Go Test
      run: make test
    - name: Go Build
      run: make build
    ################################################################################
    # GoReleaser
    ################################################################################
    - name: GoReleaser (${{ startsWith(github.ref, 'refs/tags/') && 'Release' || 'Snapshot' }})
      if: ${{ matrix.os == env.RELEASE_OS_DISTRIB && matrix.go == env.RELEASE_GO_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        make ${{ startsWith(github.ref, 'refs/tags/') && 'release' || 'snapshot' }}
    ################################################################################
    # Check Different
    ################################################################################
    - name: Check Different
      run: test "$(git diff --name-only origin/${{ github.ref_name }} | wc -l) -gt 0" && exit 1
